import { precacheAndRoute } from 'workbox-precaching';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Your web app's Firebase configuration
const firebaseConfig = {
    apiKey: process.env.FIREBASE_API_KEY,
    authDomain: process.env.FIREBASE_AUTH_DOMAIN,
    projectId: process.env.FIREBASE_PROJECT_ID,
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.FIREBASE_APP_ID,
    measurementId: "G-1PT1JS2CVS"
};

// Initialize Firebase only if config is present
if (firebaseConfig.apiKey && firebaseConfig.projectId) {
    try {
        const app = initializeApp(firebaseConfig);
        const messaging = getMessaging(app);

        onBackgroundMessage(messaging, (payload) => {
          console.log('[firebase-messaging-sw.js] Received background message ', payload);
          // Firebase automatically displays the notification if payload.notification is present.
          // We only need to handle data-only messages here if we want to show a notification for them.
          if (!payload.notification && payload.data) {
            const notificationTitle = payload.data.title || 'إشعار جديد';
            const notificationOptions = {
              body: payload.data.body || 'لديك رسالة جديدة',
              icon: '/pwa-192x192.png',
              badge: '/pwa-192x192.png',
              data: payload.data
            };
            (self as any).registration.showNotification(notificationTitle, notificationOptions);
          }
        });
    } catch (e) {
        console.error('Failed to initialize Firebase Messaging in Service Worker', e);
    }
}
